### ISSUE TITLE
Problem with connection to central unit

### ISSUE THREAD

**Issue by bertca** [ridiekel/jeletask#40]
Hi guys,

Since a few weeks i have sometimes a problem with the connection between HA and Teletask. Teletask does not react anymore on my HA-commands.  
I have no idea what is causing this, and no idea how to solve it. At the end I get it up and running again, but more on a trial and error method. This means rebooting my NUC (proxmox, portainer, HA,...), restarting my Teletask-central, alt those thing in variuos ways till thing get back to work. This morning I even reloaded my nbt-file on my Teletask-central to get it work??? 

Is there someone else encountering the same problems? Can someone interprete the error message?
The only extra information i can give is some log-entries of the jeletask docker container. Below you see the DIMMER error message, but I have the same for the relays, sensors,...

Many thanks in advance

Bert

2024-02-20 06:47:56.777 -ERROR - i.g.r.j.c.b.m.executor.MessageExecutor   : Problem running message: {"numbers":[1,2,3,4],"function":"DIMMER","acknowledged":false,"clientConfig":{"host":"192.xxx.xxx.xxx","port":55957,"type":"MICROS_PLUS"}}
io.github.ridiekel.jeletask.client.TeletaskClientImpl$CommunicationException: Problem sending message to teletask central unit
	at io.github.ridiekel.jeletask.client.TeletaskClientImpl.send(TeletaskClientImpl.java:241) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at io.github.ridiekel.jeletask.client.builder.message.messages.MessageSupport.execute(MessageSupport.java:54) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at io.github.ridiekel.jeletask.client.builder.message.executor.MessageExecutor.run(MessageExecutor.java:22) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at io.github.ridiekel.jeletask.client.builder.composer.microsplus.MicrosPlusMessageHandler$MicrosPlusGroupGetStrategy.execute(MicrosPlusMessageHandler.java:137) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at io.github.ridiekel.jeletask.client.TeletaskClientImpl$GroupGetTask.lambda$run$0(TeletaskClientImpl.java:546) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[na:na]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[na:na]
	at java.base/java.io.OutputStream.write(OutputStream.java:127) ~[na:na]
	at io.github.ridiekel.jeletask.client.builder.message.MessageUtilities.send(MessageUtilities.java:101) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	at io.github.ridiekel.jeletask.client.TeletaskClientImpl.send(TeletaskClientImpl.java:239) ~[jeletask-client-4.3.3.jar!/:4.3.3]
	... 7 common frames omitted

**Comment by ridiekel** [comment]
I had the same problem a few months back. Apparently I had a test container also running on my laptop. That container was configured with restart "always", so everytime I started my laptop, the software tried to make a connection to the central unit. Since the central unit only allows 1 connection at a time, my laptop took over and the actual prod container could no longer connect.

So most of the time if I have a connection problem, I assume I have some other leftover container running.

**Comment by bertca** [comment]
Thanks Ridiekel. 
I noticed that my old home assistant was plugged in (by accident?). Maybe this was the problem. I will keep an eye on it.

I already tried a lot of things, sometimes I got it up again for a few days, then i got the problem for some time. Rebooting everything, restarting my Micros+, ... till infinity (or till I got it working gain)
While troubleshooting, I also installed the lastest version of Prosoft (4.xx). There I noticed some problems with turning lights on and off. When I turn a light on, it works. When I push the button again (on my home assistant dashboard), The 'on' command is given again instead of the off command. In other words, the status of the light is not adjusted after the first push. No idea what is happening there...

So i rolled back to prosoft 3.8...


Bert

**Comment by ridiekel** [comment]
OK, everytime they release a new major version it can cause compatibility issues. I'll have to look into updating to v4 also at home, but can only do that when I have enough time to troubelshoot. Hopefully I will be able to take all the issues that have been logged in the recent month, and fix them properly in the near future

**Comment by bertca** [comment]
I fully understand days only have 24h ;-) Thats why i rolled back to v3.8 - so all good for me.

**Comment by claesmathias** [comment]
I'm running the very latest Teletask version and don't see any difference with the previous version. For me there sometimes a Java exception thrown and the container is stuck. When I have it next time, I will post my logs.

**Comment by claesmathias** [comment]
I would be nice if we can define a health check in docker. If you have some advice... I could Implement it logging based, but via a service would be even better.

docker top jeletask2mqtt 
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                571374              571353              1                   09:15               ?                   00:03:04            java -jar /app.jar

https://docs.docker.com/reference/dockerfile/#healthcheck

**Comment by claesmathias** [comment]
Here are some logs of today crash "Forcing refresh of states ..."
[logs.log](https://github.com/ridiekel/jeletask/files/14549573/logs.log)

**Comment by claesmathias** [comment]
A collected few more logs, command is send, but nothings happens
[logs.log](https://github.com/ridiekel/jeletask/files/14646616/logs.log)
